### ISSUE TITLE
problem with questionMessage()

### ISSUE THREAD

**Issue by LiamBradbury** [robertknight/dbpro-bluegui#1]
questionMessage() doesn't seem to work. It doesn't even highlight as a valid piece of code. I've tried uninstalling and downloading the latest version and still doesn't work. Everything else works fine.

**Comment by robertknight** [comment]
Hello Liam,

I'm afraid I'm not able to handle bug reports or support requests for this project myself as I don't have a Windows machine to work with any more. May I suggest asking for help in TheGameCreators forum?
